### ISSUE TITLE
Keeping Alternate Domain while switching to different translation

### ISSUE THREAD

**Issue by myroslav** [rtfd/readthedocs.org#1009]
I'd set up Alternate Domain according http://read-the-docs.readthedocs.org/en/latest/alternate_domains.html#cname-support. I.e. http://api-docs.openprocurement.org/ is pointing the http://openprocurementapi.readthedocs.org/ and renders properly. But when I attempt to switch to different translation via the RTD panel link:

![Screenshot](https://camo.githubusercontent.com/6f27e7fa6a9db0299f00970b3729c2c0e3cadb7a/687474703a2f2f692e696d6775722e636f6d2f57565a653062562e706e67)

I'm landing on http://openprocurementapi.readthedocs.org/uk_UA/latest/ URL instead of our custom CNAME one. I've tried configuring that as Canonical URL at https://readthedocs.org/dashboard/openprocurementapi/edit/ but it gives nothing.

**Comment by ericholscher** [comment]
This is fixed.

**Comment by marmotz** [comment]
On http://docs.atoum.org/fr/latest/ the problem is still here
"en" link is ok, but "fr" link is not

**Comment by agjohnson** [comment]
@marmotz I see both links and they seem to link correctly.

**Comment by marmotz** [comment]
I don't know where you watch, but in the bottom left menu, just after "Languages", the links are incorrect
![capture](https://cloud.githubusercontent.com/assets/932553/9423006/96d14c20-48b0-11e5-94e6-da8c5e876b06.png)

**Comment by marmotz** [comment]
And just to be sure, i've just launch a new compilation. Same results for en and fr documentation.

**Comment by gregmuellegger** [comment]
I confirm, the fr links to the readthedocs.org subdomain, the en links the CNAME setup.
Maybe is there additional setup required for the atoum-en subproject to work with the domain?

**Comment by ericholscher** [comment]
This is fixed if you create a canonical domain in the Domain section of the Admin for the project, and we will create proper CNAME'd links in all the RTD UI now. Closing this.

**Comment by Grummfy** [comment]
Hello,
for me the configuration still not working. There is still one domain for one language.
