### ISSUE TITLE
docs_dir: . is it supported?

### ISSUE THREAD

**Issue by jmcanterafonseca** [rtfd/readthedocs.org#1479]
Hi,

I would like to have the repository root as the doc_dir base. So I have configured

https://github.com/jmcanterafonseca/fiware-orion/blob/develop/mkdocs.yml

The rationale for doing so is that my README.md file has links to the other documents as well and I would like to have such a README as the home page of my doc. 

Unfortunately even though the build process finishes successfully the resulting pages are useless

http://fiware-orion.readthedocs.org/en/develop/

Any idea?

thanks, best

**Comment by d0ugal** [comment]
I see you have `docs_dir: ./` - can you try `.` and remove the slash?

**Comment by jmcanterafonseca** [comment]
I've tried without the slash and the same happens

2015-07-22 12:56 GMT+02:00 Dougal Matthews <notifications@github.com>:

**Comment by d0ugal** [comment]
I'm not sure, I built this locally with MkDocs and it worked fine. The issue is somewhere in the ReadTheDocs integration code.

**Comment by jmcanterafonseca** [comment]
yes as per my investigations it seems that the paths to the CSS is not set
properly on the pages

2015-07-22 13:13 GMT+02:00 Dougal Matthews <notifications@github.com>:

**Comment by telemachus** [comment]
I'm seeing this as well: http://split.readthedocs.org/en/latest.

Also for what it's worth, if I didn't add `docs_dir` to the configuration file, then `./README.md` was ignored. My understanding was that it would be checked as a fallback (after looking in `./doc`). Is that wrong?

**Comment by agjohnson** [comment]
Looks like the original issue is resolved here?

**Comment by stsewd** [comment]
Is anyone still having this issue? I checked the projects here: the first seems like the docs_dir was moved, and the second project doesn't exist.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
