### ISSUE TITLE
GitHub aggressively caches status badges: need HTTP headers to prevent it.

### ISSUE THREAD

**Issue by nedbat** [rtfd/readthedocs.org#1612]
My "docs status" badge is stuck on red, because GitHub caches them.  Here's the GitHub issue discussing the caching headers needed: https://github.com/github/markup/issues/224  I'm not sure rtfd's redirect to shields.io affects things.

**Comment by agjohnson** [comment]
Agreed, we should be doing this. If we can't do this in the badge view, we can do it in the production environment.

**Comment by mattions** [comment]
+1 on this one

**Comment by gregmuellegger** [comment]
Possible fix: #1653

**Comment by flavio** [comment]
I'm still affected by this issue even though the code has been merged.

**Comment by tbleiker** [comment]
Same here...

**Comment by wishstudio** [comment]
+1 to this issue.

**Comment by jonasrauber** [comment]
This problem still exists. According to [`GitHub`](https://github.com/github/markup/issues/224), the solution is to set `Expries`, `Last-Modified` or `Etag` in addition to `Cache-Control: no-cache`, which is not happening right now.

> We're pretty confident that the image caching works. If you're having issues with something like a CI badge, make sure the image has the Cache-Control: no-cache header, and either Expires, Last-Modified or Etag. See the Fastly documentation for more info.

**Comment by jonasrauber** [comment]
I created a pull-request to fix this: #2927

**Comment by ericholscher** [comment]
Should be fixed by https://github.com/rtfd/readthedocs.org/pull/3005 :+1:

**Comment by fritzo** [comment]
I'm still seeing this issue. To reproduce:
1. create a new rtfd project with broken build
2. add a badge to the project's github README.md
3. fix the rtfd build

**Comment by Parker8283** [comment]
I am also still seeing this issue with my [School Project Repo](https://github.com/TInventory/Program). The builds were failing, they were fixed about 3 days ago, but the failing badge still persists.
