### ISSUE TITLE
mkdocs build flow supports submodule?

### ISSUE THREAD

**Issue by gianarb** [rtfd/readthedocs.org#1618]
Hi! I'm working on this project
https://github.com/gianarb/penny/tree/feature/layout-docs

I read #606 issue but it seem doesn't works for my case.. This feature is not supported by mkdocs build flow?

Thanks

**Comment by agjohnson** [comment]
Yes, submodule support is baked into the git backend, independent of sphinx or mkdocs backends.

**Comment by gianarb** [comment]
I can do this process from read the docs build? How can I manage this flow?

Thanks a lot!

**Comment by agjohnson** [comment]
You shouldn't need to do anything to invoke submodules. Is there a specific issue to solve here? Which project are you having problems with?

**Comment by gianarb** [comment]
Yes sorry this project https://github.com/gianarb/penny/tree/feature/playout

This is the last build 
https://readthedocs.org/projects/penny/builds/3290310/

**Comment by agjohnson** [comment]
This seems to be a mkdocs issue. I see the submodule is pulled in successfully, this should work if mkdocs is configured correctly. Can you verify you are running `mkdocs==0.14.0` locally, and that the path isn't an issue running the same command:

```
mkdocs build --clean --site-dir _build/html --theme readthedocs
```

**Comment by gianarb** [comment]
It works in my local env but I already resolved playout submodule

**Comment by agjohnson** [comment]
I don't think this is a submodule issue. This branch works on my local instance of RTD.

**Comment by gianarb** [comment]
eheh sorry but I have not a strong experience with read the docs.. How can
I help you to debug this issue?

2015-09-01 23:00 GMT+02:00 Anthony <notifications@github.com>:

> I don't think this is a submodule issue. This branch works on my local
> instance of RTD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1618#issuecomment-136860238>
> .
>



-- 
Gianluca Arbezzano
www.gianarb.it

**Comment by gianarb** [comment]
Any idea to solve this problem?

**Comment by gregmuellegger** [comment]
There seems to be a successfull build for the `feature-playout` branch: https://readthedocs.org/projects/penny/builds/3298098/

@gianarb Does this mean that the the issue is resolved for you?

**Comment by gianarb** [comment]
Hi @georgedorn :) No the problem persist. `feature-playout` is a temporary solution, in this branch I don't use a submodule but I added directly the theme directory into the vcs..

**Comment by gregmuellegger** [comment]
The docs with missing layout here http://penny.readthedocs.org/en/feature-playout/ come from this build: https://readthedocs.org/projects/penny/builds/3298098/

The hash for the build is 17c8816f902e00c6caea567d398ececae0db763b, here is the your repos tree at this commit: https://github.com/gianarb/penny/tree/17c8816f902e00c6caea567d398ececae0db763b

I think the reason that the submodules where not initialized is that the repo did not contain the `.gitsubmodules` file. You need to check this file in to let other clones know about the submodules.
See here for a tutorial on submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules

@gianarb can you test again by checking in your `.gitsubmodules` file and triggering a new build?

**Comment by gianarb** [comment]
@gregmuellegger I tried to do order :) I did a lof ot tests and the scope is not clean :)

This is my last test branch https://github.com/gianarb/penny/tree/feature/doc-submodule and this is the build
https://readthedocs.org/projects/penny/builds/3304669/

I don't understand why it is broken.. playout directory exists how submodule

**Comment by gregmuellegger** [comment]
@gianarb sorry for gropping in the dark here a little. like @agjohnson I tested this locally on my installation and the submodules are getting checked out correctly. The only thing left I can think of is that the checkout on the servers are corrupt somehow. Can you please try wiping your build environment for the `feature/doc-submodule` version with the button on https://readthedocs.org/projects/penny/versions/ and then trigger a new build here: https://readthedocs.org/projects/penny/builds/

**Comment by gianarb** [comment]
After wipe the problem persist
https://readthedocs.org/projects/penny/builds/3305399/

:(

**Comment by gianarb** [comment]
@gregmuellegger I tried to create new project with same codebase but nothing
https://readthedocs.org/projects/penny-test/builds/3307741/

**Comment by ericholscher** [comment]
Is this still an issue?

**Comment by gianarb** [comment]
yes

**Comment by humitos** [comment]
Closing. The project was removed from RTD (all the links pointing to RTD are dead).

I'm not sure how to reproduce the issue, but reading the comments, it seems that the `.gitsubmodule` file was missing.

Please, feel free to reopen if you consider.

**Comment by barseghyanartur** [comment]
@humitos:

Please, reopen.

It's currently a problem in [this project](https://github.com/barseghyanartur/django-fobi). Any help is highly appreciated.

**Build error**

Build #6247771
0.12.5
Build failed
Having trouble with your build environment? Try reseting it.

Error

Failed to import project: Failed to get code from 'https://github.com/barseghyanartur/django-fobi' (git clone): 1 git clone error output: Cloning into 'examples/wagtaildemo'... Permission denied (publickey).
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Clone of 'git@github.com:barseghyanartur/wagtaildemo.git' into submodule path 'examples/wagtaildemo' failed

**Comment by barseghyanartur** [comment]
@RichardLitt:

Thanks! I had to switch to BitBucket (where I didn't have Git sub-modules) in order to have the docs working. But if I switch back to GitHub, the problem returns.

**Comment by stsewd** [comment]
@barseghyanartur As you mention here https://github.com/rtfd/readthedocs.org/issues/3020#issuecomment-354030446 your issue was solved. Can we close this now? or there is another project with this issue?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, the other problem was fixed on https://github.com/rtfd/readthedocs.org/issues/3020#issuecomment-354030446

**Comment by barseghyanartur** [comment]
@stsewd:

Sorry! I didn't notice your question. Yes, the issue is solved for me by switching to BitBucket, where I don't have git sub-modules (I use Mercurial there). It did seem to work (on GitHub) with `Programming Language` set to `Only Words` (instead of `Python` in settings). Without the change it kept failing. But then again something broke and I just made it simple for myself, by switching to BitBucket. It seemed like spending too much time on something I could solve easily.
