### ISSUE TITLE
Support specifying 'python setup.py build_sphinx' as an alternative build command

### ISSUE THREAD

**Issue by tjanez** [rtfd/readthedocs.org#1857]
According to [Build Process documentation](http://docs.readthedocs.org/en/latest/builds.html?highlight=build#understanding-what-s-going-on), RTD's build process runs:

```
sphinx-build -b html . _build/html
```
to build the documentation (`html` being replaced with the correct backend).

Would it be possible to support specifying an alternative build command, e.g.:

```
python setup.py build_sphinx
```

A nice advantage why I'm using `python setup.py build_sphinx` in my projects is that it allows one to avoid redefining project's `project`, `version`, `release` and `copyright` variables by specifying the following in `setup.py`:

```python
    command_options={
        'build_sphinx': {
            'project': ('setup.py', name),
            'version': ('setup.py', version),
            'release': ('setup.py', release),
            'copyright': ('setup.py', copyright),
        }
    }
```

Using the above, these values are defined only once in a project.

**Comment by agjohnson** [comment]
I'm -0 on this change, there are several other ways around this already, and we're working in another direction to simplify the configuration process. This is also an option specific to Python, we're moving more towards language-agnostic options.

**Comment by ericholscher** [comment]
Agreed. Closing this, as we pass specific configuration to the sphinx build, and supporting vanity invocations isn't a good idea for us.

**Comment by tivaliy** [comment]
For some reason I need to run build as:
`python setup.py build_sphinx`
So is it possible to invoke command in a such way using `readthedocs.yml` or any other approach (configuration process)?

**Comment by jonas-eschle** [comment]
> For some reason I need to run build as: `python setup.py build_sphinx` So is it possible to invoke command in a such way using `readthedocs.yml` or any other approach (configuration process)?

What is the reason behind this? Maybe the issue is solved in a better way differently

**Comment by humitos** [comment]
In case this is still an issue for anybody, you can take a look at https://docs.readthedocs.io/en/latest/build-customization.html that allows you to run extra commands on Read the Docs build process.
