### ISSUE TITLE
Github integration doesn't support a list for source_suffix

### ISSUE THREAD

**Issue by mgeier** [rtfd/readthedocs.org#1871]
A custom `source_suffix` is supported (see #559), but if `source_suffix` is a list of suffixes, apparently only the first one is taken into account.
This leads to broken Github links to source files using any of the other suffixes.

**Comment by ericholscher** [comment]
This is fixed, but depends on Sphinx's page_source_suffix. https://github.com/sphinx-doc/sphinx/issues/2278 is trying to get that in a proper sphinx release. I thought it was already released.

**Comment by mgeier** [comment]
This still doesn't work for me ...

Is this supposed to work now?

If yes, I'll have to investigate further ...

**Comment by agjohnson** [comment]
No, this shouldn't be fixed yet. Looks like the 1.3.6 release has this fix, we need to bump up to this release. You can specify a specific Sphinx version with your requirements file however.
