### ISSUE TITLE
Built documentation is out of date

### ISSUE THREAD

**Issue by SteveDoyle2** [rtfd/readthedocs.org#1971]
Per the "latest" build for my project, the latest push to the master is **correctly** found.  The latest build is has a has of 1b67562c0781794301bf05c619a36602efb9b7d5.  This information is found at:

https://readthedocs.org/projects/pynastran-git/builds/3689696/

The documentation for the latest is thus (the problem region is shown):
http://pynastran-git.readthedocs.org/en/latest/_modules/pyNastran/bdf/bdf.html#BDF

The documentation, it is not consistent with the the specified build.  One such file is found at:
https://github.com/SteveDoyle2/pyNastran/blob/1b67562c0781794301bf05c619a36602efb9b7d5/pyNastran/bdf/bdf.py

The ``__init__`` begins on line 247 of this file and is inconsistent with the RTD documentation link.

I suspect some build files have not been properly cleaned out.  Is there anything I can do to fix this?

**Comment by lurch** [comment]
I'm seeing something similar too - I noticed that a recently-updated doc ( https://github.com/PyFilesystem/pyfilesystem/commit/20efe88158f5de4b680c901eba96de7a006a9ef1 ) was out of date on http://docs.pyfilesystem.org/en/latest/getting_started.html so I tried to trigger a manual rebuild, and RTD then complained about `wx` being in requirements.txt ( http://readthedocs.org/projects/pyfilesystem/builds/3700600/ ), which is something I fixed over an hour previously! https://github.com/PyFilesystem/pyfilesystem/commit/352ee57b07d44471db50f4a13b37a47806584d7b

Seems like RTD is somehow getting **old** versions of the Github source?

**Comment by SteveDoyle2** [comment]
I forgot to mention, RTD is getting old source code, but not old ``conf.py`` or committed RST files.  Wiping the build does not fix it.

**Comment by lurch** [comment]
I just created an account on RTD and linked it to my github account to see if that would make any difference. I tried forcing another rebuild ( http://readthedocs.org/projects/pyfilesystem/builds/3700755/ ), and it's now grabbed commit-hash c1d94ae227b3b684929a08eb3a641a794e0f9fca which is (a bit better but) still behind the latest version of https://github.com/PyFilesystem/pyfilesystem/commits/master (currently at 20efe88158f5de4b680c901eba96de7a006a9ef1 ).

**Comment by lurch** [comment]
...and I've just pushed another commit https://github.com/PyFilesystem/pyfilesystem/commit/0f5bc2b68a38dae312e1888a79c16551d8f54e6d which triggered an auto-rebuild on RTD http://readthedocs.org/projects/pyfilesystem/builds/3700773/ and for some reason it's jumped back to the old version 191a54467a93cf9d497ce77b00d3e61f9ca28404 of the source again :-(

**Comment by agjohnson** [comment]
@SteveDoyle2 looks like the most recent build has the most recent commit

@lurch not quite sure why the builds are gravitating towards that commit. A manual rebuild pulled the correct commit though.

This could have been an intermittent issue, given both happened in the same time frame. Perhaps the time frame coincides with the GitHub outage?

**Comment by agjohnson** [comment]
Also, have either of these projects had a branch/tag/etc named 'latest' at any point?

**Comment by SteveDoyle2** [comment]
No.  I did have a "master" RTD build because I wanted it to be consistent with my branch names.  Removing that maybe helped things.  I removed it in an effort to get my project to build.  I removed that right around the time Github went down, which broke other things, but I'm not sure what happened first.

**Comment by lurch** [comment]
> had a branch/tag/etc named 'latest' at any point?

Nope. I've just kicked off my own manual-rebuild of the PyFilesystem RTD and it's remained at the 'correct' version now (so perhaps the problem is fixed), but I'll continue to keep an eye on it.

**Comment by agjohnson** [comment]
Well if this resurfaces, the versions may need to be reconfigured -- a branch named `latest` or `stable` will cause our code to not auto-advanced it's `latest` and `stable` pointer versions.

I'll close this for now, as it sounds like both projects are behaving as normal, but feel free to reopen.

**Comment by SteveDoyle2** [comment]
I'm still having problems with this issue.  I wiped the build, but that did not help.  Is there any easy way I can remove the "latest" build and recreate it?


As before, the RST files I wrote are correctly applied to the documentation.
http://pynastran-git.readthedocs.org/en/latest/quick_start/gui.html#scripting

Additionally, the hash is correct.

The RST files that sphinx autogenerated are very old.
http://pynastran-git.readthedocs.org/en/latest/_modules/pyNastran/bdf/bdf.html#BDF

Comparing to the previous link to the following source on line ~254, it's easy to see the RTD source is out of date.  Self has been removed from the docstring.
https://github.com/SteveDoyle2/pyNastran/blob/master/pyNastran/bdf/bdf.py

**Comment by agjohnson** [comment]
Are you certain this isn't an issue with local caching? The generated files appear to match the source file you linked to, and the docstrings look how I'd expect. Additionally, the correct git hash is at the bottom of the page.

**Comment by SteveDoyle2** [comment]
> Are you certain this isn't an issue with local caching? 

I'm sorry.  I don't think I follow.  I believe there is local caching on the RTD side.  When I generate documentation locally, it looks correct.  On the RTD side, it appears the parts I wrote by hand are correct, but the auto-generated class/function documentation based on actual source code is out of date.
