### ISSUE TITLE
web3j build is stuck & subsequent builds all fail due to a file lock issue

### ISSUE THREAD

**Issue by conor10** [rtfd/readthedocs.org#2476]
## Details
- Project URL: https://readthedocs.org/projects/web3j/
- Build URL (if applicable): https://readthedocs.org/projects/web3j/builds/4575723/
- Read the Docs username (if applicable): conor10
## Expected Result

Build should complete.
## Actual Result

Build has been stuck for over 2 hours

**Comment by conor10** [comment]
Subsequent builds are now not working either, so I can't update the web3j docs :-(

Build #4576621
latest
Build failed
Error

[Errno 30] Read-only file system: '/home/docs/checkouts/readthedocs.org/user_builds/web3j/latest__rtdlock'

**Comment by krzychb** [comment]
## Details

* Project URL: https://readthedocs.org/projects/esp-idf/
* Build URL (if applicable): https://readthedocs.org/projects/esp-idf/builds/4577311/
* Read the Docs username (if applicable): krzychb

## Expected Result

Build should complete.

## Actual Result

I believe I see the same issue. Attempted to build two times and each time the build fails just after start. The following error is reported:
```
[Errno 30] Read-only file system: '/home/docs/checkouts/readthedocs.org/user_builds/esp-idf/latest__rtdlock'
```
![image](https://cloud.githubusercontent.com/assets/12953787/19806977/2f071f98-9d1e-11e6-9941-84274b79ebb6.png)

**Comment by krzychb** [comment]
The issue with builds on my repository have been resolved with https://github.com/rtfd/readthedocs.org/issues/2475#issuecomment-256993674
Thanks!

**Comment by conor10** [comment]
Thanks for letting me know @krzychb. Unfortunately my builds are still hanging at the below point every time.

<img width="861" alt="screen shot 2016-10-30 at 20 34 35" src="https://cloud.githubusercontent.com/assets/2148266/19835620/7da91296-9ee0-11e6-9aac-e40b5849ad7c.png">

**Comment by conor10** [comment]
I've tried deleting & recreating my project, but still encounter the same issues unfortunately.

**Comment by krzychb** [comment]
Hi conor10,

I am sorry to hear that. I have a new case when my build started off, step by step very slowly, to finally get stuck like below.

![image](https://cloud.githubusercontent.com/assets/12953787/20204165/a8634b50-a7cd-11e6-9327-9e6067b94fd6.png)

It is still like that. I do not see the clue in the log why is it so.

Then, after an hour or so, I have started another build and this one passed in 123 seconds

![image](https://cloud.githubusercontent.com/assets/12953787/20204232/3b7b3fc4-a7ce-11e6-800d-b84bbf4868b9.png)

I am using Read the Docs just for coupe of weeks now and do not have much experience.

In this case, as you already did "deleting & recreating your project", I would check the [Barebones example of a ReadTheDocs repo](https://github.com/Cruel/readthedocs-breathe). This is to rule out your current repository as potential source of issues,

I have started with this particular example and it worked for me from the first try.

Krzysztof

**Comment by conor10** [comment]
I tried switching to that repository, and still ran into issues:

![screen shot 2016-11-16 at 10 39 09](https://cloud.githubusercontent.com/assets/2148266/20328834/0a6bb548-abe9-11e6-8f8c-e751161b8aac.png)
![screen shot 2016-11-16 at 10 39 35](https://cloud.githubusercontent.com/assets/2148266/20328841/158a9a66-abe9-11e6-9fc7-e715830800fa.png)

**Comment by humitos** [comment]
@conor10 it seems your last build is passing. What did you change? Is your issue solved? Let me know if we can close this one.

**Comment by conor10** [comment]
Looks like this is working now (I missed the above message and haven't checked RTD in months as I was updating docs manually instead).

I didn't ever change anything on my side. It magically started working again.
