### ISSUE TITLE
Sphinx build failed with unknown error.

### ISSUE THREAD

**Issue by madskinner** [rtfd/readthedocs.org#3276]
## Details

* Project URL: https://readthedocs.org/projects/pub2sd/
* Build URL (if applicable):https://readthedocs.org/projects/pub2sd/builds/6277134/
* Read the Docs username (if applicable): silseb

## Expected Result
Tried to build the documents following a 'git push' to "https://github.com/madskinner/pub2sd"

## Actual Result
The build failed with Error: Unknown error encountered. Please include the build id (6277336) in any bug reports.
Sphinx build for 'building [readthedocssinglehtmllocalmedia]' apparently passed, but error occurred immediately after or at start of next build.

Retrying with PDF and EPUB build disabled in 'Advanced Settings' made no difference. Likewise clearing as many warnings as I could, made no change.

**Comment by piogor** [comment]
In my case the similar problem was solved by putting `Sphinx>=1.6.5` into `requirements.txt`. The Sphinx version 1.5.6 (as it was used to build your project, too) provided corrupted latex output.

**Comment by madskinner** [comment]
Thanks for the suggestion 'Piogor', just tried it. Unfortunately it still fails at the same point even though the log shows it running Sphinx 1.6.5 in build:
https://readthedocs.org/projects/pub2sd/builds/6280898/

**Comment by agjohnson** [comment]
Thanks for the report @madskinner, this is an uncaught error in our build system. We're trying to surface these more in hopes of actually creating a caught error.
