### ISSUE TITLE
Badges aren't updating due to being cached on GitHub.

### ISSUE THREAD

**Issue by MikeHart85** [rtfd/readthedocs.org#3323]
## Details

* Project URL: https://github.com/DMSC-Instrument-Data/lewis

Probably affects everyone that uses badges. At least on GitHub.

Our RTFD badge has been showing "failing" for days now, even though the docs build successfully.

Appears to be happening because GitHub has the image cached on its own domain.

Had a look at HTTP headers:

https://readthedocs.org/projects/lewis/badge/?version=latest
> 302 Redirect
> Cache-Control: "no-cache, no-store, must-revalidate, max-age=0"

https://media.readthedocs.org/static/projects/badges/passing.svg
> 200 OK
> Cache-Control: "max-age=604800"

Seems likely that GitHub is ignoring the Cache-Control of the initial URL and respecting the Cache-Control of the redirect target... which means the badge will be cached for 604800 seconds == 7 days.

Related issues: #1612 and #3000.
Appears fixed in: https://github.com/rtfd/readthedocs.org/commit/8c37801e326e41be2100fb97b943986fbd935d8f#diff-5d1a334650edab756ce4cdf8c531111e
Likely reintroduced by: https://github.com/rtfd/readthedocs.org/commit/91f6c084a68ab8a2f6607a028f60d56854d0b1c4#diff-5d1a334650edab756ce4cdf8c531111e

Note the latter commit was on Aug 17. Two new comments against #1612 since then complain that the problem still exists. Comments dated Aug 21 and Oct 31.

## Expected Result

Badge should update when build status changes.

## Actual Result

Badge doesn't update because it is cached.

**Comment by ericholscher** [comment]
So we need to add the max age back in?

**Comment by ericholscher** [comment]
I believe I can set this on nginx just for the badges directory, and it should fix it.

**Comment by ericholscher** [comment]
Did some testing. Does this look like it will fix it?

```
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 08 Dec 2017 15:22:16 GMT
Content-Type: image/svg+xml
Content-Length: 790
Connection: keep-alive
Last-Modified: Friday, 08-Dec-2017 15:22:16 GMT
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
X-Deity: web01
Access-Control-Allow-Origin: *
X-Served: Nginx
Accept-Ranges: bytes
```

**Comment by dseuss** [comment]
I still see the project in our [project](https://github.com/dseuss/mpnum)

Here is what the github people say: https://github.com/github/markup/issues/224

**Comment by ericholscher** [comment]
Believe this should be fixed.

**Comment by piccolbo** [comment]
I can see it right now on my project:
https://github.com/piccolbo/altair_recipes

Badge is red but docs are right there in place. Last failed build close to two days old. Loading the image separately (per rst file) results in a green badge. The image appears to be cached by github per address bar if I open the image alone. Other badges are moving along just fine.

**Comment by piccolbo** [comment]
Never mind I see there's a three days old fix. Hopefully it will kick in at some point.

**Comment by piccolbo** [comment]
Will keep an eye on it thanks.

**Comment by sjspielman** [comment]
+1 This is ongoing. Any fixes?

**Comment by ericholscher** [comment]
We are still setting the cache headers, do you have more information about this issue?

**Comment by webappsforindustry** [comment]
Add cache-control=no-cache as a parameter to your URL. per example:
Old URL = https://tryhackme-badges.s3.amazonaws.com/secutest.png?style=flat
New URL = https://tryhackme-badges.s3.amazonaws.com/secutest.png?style=flat&cache-control=no-cache
