### ISSUE TITLE
Unable to use Sphinx 1.6.5 on 3.5 environment

### ISSUE THREAD

**Issue by Rapptz** [rtfd/readthedocs.org#3460]
## Details

* Project URL: https://readthedocs.org/projects/discordpy/
* Build URL (if applicable): https://readthedocs.org/projects/discordpy/builds/6471244/
* Read the Docs username (if applicable): Rapptz

## Expected Result

The build to run successfully.

## Actual Result

The build fails.

There have been multiple setuptools/pip related issues when building my project (probably unrelated, see: [here](https://readthedocs.org/projects/discordpy/builds/6471235/) and [here](https://readthedocs.org/projects/discordpy/builds/6470769/), and related issue [here](https://github.com/pypa/setuptools/issues/885)) but once the build environment is wiped and fixed the above issue with sphinxcontrib-websupport is realised.

Essentially, for some reason the virtual environment provided by RTD fails to import the `sphinxcontrib.websupport` package which is required for previous usage of `sphinx.websupport` (which was deprecated and split up in v1.6). The logs *do* show a successful installation of the contrib package, and in fact it comes as a requirement with v1.6 of Sphinx.

I cannot reproduce this issue with a local build of the docs. Wiping the build environment does not fix the issue.

**Comment by danwos** [comment]
Can confirm this bug. 
Currently no working builds with Python3.5.
Detailed error:
```
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/sphinx/websupport/__init__.py:27: UserWarning: Since Sphinx-1.6, sphinx.websupport module is now separated to sphinxcontrib-websupport package. Please add it into your dependency list.
  warnings.warn('Since Sphinx-1.6, sphinx.websupport module is now separated to '

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/readthedocs_ext/readthedocs.py", line 15, in <module>
    from .comments.builder import (finalize_comment_media, ReadtheDocsBuilderComments,
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/readthedocs_ext/comments/builder.py", line 7, in <module>
    from . import backend, translator
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/readthedocs_ext/comments/backend.py", line 6, in <module>
    from sphinx.websupport.storage import StorageBackend
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-needs/envs/2.0/lib/python3.5/site-packages/sphinx/websupport/storage/__init__.py", line 12, in <module>
    from sphinxcontrib.websupport.storage import StorageBackend  # NOQA
ImportError: No module named 'sphinxcontrib.websupport'
```
Project + example build: https://readthedocs.org/projects/sphinxcontrib-needs/builds/6747648/

sphinxcontrib-websupport gets collected during installation phase:
```
Collecting sphinxcontrib-websupport (from sphinx==1.6.5)
  Using cached sphinxcontrib_websupport-1.0.1-py2.py3-none-any.whl
```
Switching to Python 2.7 solves the problem.

**Comment by humitos** [comment]
Hi! This seems to be a problem related to the virtual environment itself. Did you try wiping it? Could you try that and let us know?

**Comment by danwos** [comment]
Yes, that was the first thing I tried. 
Unluckily it hasn't worked.

**Comment by Rapptz** [comment]
Sorry for bumping this but my RTD builds have been failing for almost 3 months now.

**Comment by stsewd** [comment]
@Rapptz have you take a look at https://github.com/sphinx-doc/sphinx/issues/3683? Seems like this was a bug on sphinx and was already solved, but with some changes on he requirements.

Also, I was trying to replicate your issue, but seems like your build now are falling for other reason.

**Comment by Rapptz** [comment]
Yes I've seen that issue before, it's not related to the current failures. I'm using the release version of Sphinx not the beta versions. The build is still failing with the stuff I have in the OP. 

First failure is the websupport related: `Could not import extension readthedocs_ext.readthedocs (exception: No module named 'sphinxcontrib.websupport')` ([failing build](https://readthedocs.org/projects/discordpy/builds/6850293/))

Second failure is for some strange pip related issue (which I guess I can fix by bumping the setuptools but I don't want to mess with the venv like that): `    AttributeError: '_NamespacePath' object has no attribute 'sort'` (pypa/setuptools#885) and [the failing build](https://readthedocs.org/projects/discordpy/builds/6854243/)

**Comment by stsewd** [comment]
@Rapptz Were you able to solve the problem?

**Comment by Rapptz** [comment]
I just bumped Sphinx and used the yaml format instead and that seemed to fix it.
