### ISSUE TITLE
Code formatting works locally but not on ReadTheDocs.org

### ISSUE THREAD

**Issue by amit1rrr** [rtfd/readthedocs.org#4072]
## Details

* Read the Docs project URL: docs.nurtch.com
* Build URL (if applicable): 
* Read the Docs username (if applicable): amit.juschill@gmail.com

## Expected Result

I am expecting python code snippets to be syntax highlighted on ReadTheDocs.org.  It's working fine locally where I have readthedocs theme installed.  I am using code block. Here is the snippet example inside .rst file:

```
   .. code-block:: python

      from rubix.aws.cloudwatch import plot_metric

      # Load balancer P90 latency with deployment time markers
      plot_metric(namespace='AWS/ELB',
            metric_name='Latency',
            dimensions={'LoadBalancerName': 'prod-xyz-lb'},
            markers=deployment_times,
            statistics='p90')

      # Maximum CPU Utilization across EC2 for a specific time period
      plot_metric(namespace='AWS/EC2',
            metric_name='CPUUtilization',
            start_time=datetime.datetime(2018, 04, 25),
            end_time=datetime.datetime(2018, 04, 26)
            statistics='Maximum')
```

Screenshots attached.

Local Build.
<img width="738" alt="local_build_output" src="https://user-images.githubusercontent.com/1350490/39810567-0ff8b0ac-53a3-11e8-9d1e-20b18dd05d3f.png">

On my hosted domain
<img width="747" alt="on-readthedocs-org" src="https://user-images.githubusercontent.com/1350490/39810568-10241ddc-53a3-11e8-8e96-1fda54fd32cd.png">

**Comment by ivankravets** [comment]
The same problem http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#before-pre-and-after-post-actions

**Comment by ivankravets** [comment]
It seems duplicate of https://github.com/rtfd/readthedocs.org/issues/4050

**Comment by amit1rrr** [comment]
> It seems duplicate of #4050

Yes, looks like the same issue. Workaround is to explicitly specify the version of `sphinx_rtd_theme`
sphinx_rtd_theme>=0.3.1

I don't have any requirements.txt in my repository. There is one scant reference to it in the docs:
http://docs.readthedocs.io/en/latest/faq.html?highlight=requirements.txt#my-project-isn-t-building-with-autodoc

Basically, I need to go to Advanced settings and enable build with virtualenv and specify the requirements.txt file there. My questions is: what are all dependencies of building RTD.

Should these be enough: 
https://github.com/shawnbrown/datatest/commit/66f845531854692f74725e5fab1037f418a25695

**Comment by amit1rrr** [comment]
My issue is resolved. 

Steps for other folks:
- Go to Advanced Settings and select this option: `Install your project inside a virtualenv using setup.py install`
- Add requirements.txt file to the text box on Advanced settings (see screenshot)
- Scroll down and select this option as well: `Give the virtual environment access to the global site-packages dir.`
- Create requirements.txt file in your project root with only this line:
`sphinx_rtd_theme>=0.3.1`
- Commit the project and verify that the build succeeds on RTD. 
- Code should have syntax highlighting

Screenshots:

<img width="977" alt="11" src="https://user-images.githubusercontent.com/1350490/39823891-a6400ad8-53cb-11e8-999c-17b387bf4855.png">
<img width="582" alt="12" src="https://user-images.githubusercontent.com/1350490/39823903-ad4791ca-53cb-11e8-8ed2-a290af3785f0.png">

**Comment by RichardLitt** [comment]
Thank you, @amit1rrr, for both logging and resolving your issue! Glad you got it fixed.

**Comment by ivankravets** [comment]
@RichardLitt I'm not sure that a thousand developers should do the same. I think it should be fixed on RTFD side.

**Comment by stsewd** [comment]
@ivankravets yeah, we didn't update the package on rtd because of a previous bug on the 0.3 version of the theme. But now that is fixed.

**Comment by amit1rrr** [comment]
After I followed those steps a couple of builds went fine and I started seeing this error:
```python: can't open file 'setup.py': [Errno 2] No such file or directory```

And rightly so, because if we have selected to install a project inside virtual env with setup.py then we need to write our own setup.py :( I am not sure why it succeeded the first few time.

Now spending time writing a setup.py to get my original issue of code formatting working is not worth it. @stsewd since the theme issue is fixed can of you update the package on rtd?

**Comment by amit1rrr** [comment]
I just made an attempt at simple setup.py that worked. 
https://github.com/amit1rrr/nurtch-docs/blob/master/setup.py

For others: Everyone shouldn't have to do all this to get syntax highlighting working for code blocks. Seems like an essential feature for any documentation system.

**Comment by stsewd** [comment]
I can say that the `Install project` option isn't required for your project, you only need the `requirements.txt` file

**Comment by amit1rrr** [comment]
Worked fine after wiping. I think the rtfd package would have got cached or something. Shouldn't `wipe` be default internal steps on RTD builds.

**Comment by amit1rrr** [comment]
> This step is almost no need it, just in exceptional cases like this one.

I'm not sure about that. I have had inconsistent results twice in my first 2 weeks with RTD (documented in this thread above). While there is nothing exceptional in my build/package/config. 
If it's package caching issue then at least every build that specifies requirements.txt should have wipe option enabled.

**Comment by stsewd** [comment]
We can close this, as the original issue was solved. I think there is already a follow up by the rtd team to upgrade the theme on the rtd side.

**Comment by ivankravets** [comment]
@stsewd I did “wipe” for docs.platformio.org and it still doesn’t work without a custom requirements.txt

Should it work without extra steps as in the previous years?

**Comment by stsewd** [comment]
@ivankravets yes, you need a requirements file with the rtd_theme version that fixes the syntax.

**Comment by stsewd** [comment]
And as mention, rtd only needs to upgrade the default version of the theme and then you wouldn't need a requirements file.

**Comment by ivankravets** [comment]
Do you have any ETA when you will have this fixed on your side?

**Comment by davidfischer** [comment]
> Do you have any ETA when you will have this fixed on your side?

Probably within a week. We generally don't limit ourselves with strict timelines.

**Comment by davidfischer** [comment]
I re-opened #4050 until #4096 is merged. I think that's for the best so people can find it.

As to what it takes to get this working *now*, you need to pin to `sphinx_rtd_theme>=0.3.1`. Both of the two threads discuss that.
