### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN for assets.readthedocs.org

### ISSUE THREAD

**Issue by segevfiner** [rtfd/readthedocs.org#4660]
Read the Docs is loading without static assets for me. When browsing to `assets.readthedocs.org`, I'm getting an an `SSL_ERROR_BAD_CERT_DOMAIN` (Firefox), meaning all `readthedocs.org` static assets don't load.

![image](https://user-images.githubusercontent.com/24731903/45919276-61834000-be9b-11e8-8810-8616c1caf4c3.png)

![image](https://user-images.githubusercontent.com/24731903/45919265-3c8ecd00-be9b-11e8-87a3-c414b6e392d9.png)

**Comment by stsewd** [comment]
Looks good from my side

**Comment by segevfiner** [comment]
`assets.readthedocs.org` gets resolved to `13.107.246.10` here.

**Comment by davidfischer** [comment]
> assets.readthedocs.org gets resolved to 13.107.246.10 here.

Resolves to the same here.

I looked at this on a few different browsers (including a couple versions of FF) and it looks good to me. I'm guessing this was a temporary hickup on the Microsoft CDN. Are you still seeing it?

**Comment by stsewd** [comment]
Resolving to the same IP here too

**Comment by segevfiner** [comment]
> Are you still seeing it?

Sadly yes... 😢

**Comment by davidfischer** [comment]
>>> import requests
    >>> requests.get("https://assets.readthedocs.org")  # there's nothing at the root, 400 is correct
    <Response [400]>
    >>> requests.__version__
    '2.18.4'

**Comment by davidfischer** [comment]
At least one other user is reporting this issue on [twitter](https://twitter.com/_heartsucker/status/1043557933869682688).

**Comment by segevfiner** [comment]
> That looks like Firefox on Windows. Is that correct? If you wouldn't mind could I get the exact version number and at least the major OS version? You aren't by chance running a nightly or anything, right? Are you seeing this exclusively on Firefox? Not other browsers?

Firefox 62.0 on Windows 10.0.17134.285 x64 and Chrome 69.0.3497.100 on Android 8.1

**Comment by davidfischer** [comment]
I just tested on Firefox 62.0.2 (MacOS) and Chrome 69.0.3497.100 (same version) on Android 9 without issue. This leads me to believe it is an issue with the CDN itself and not a browser incompatibility.

One more question, geographically which country is your connection coming from?

**Comment by segevfiner** [comment]
> 
> 
> I just tested on Firefox 62.0.2 (MacOS) and Chrome 69.0.3497.100 (same version) on Android 9 without issue. This leads me to believe it is an issue with the CDN itself and not a browser incompatibility.
> 
> One more question, geographically which country is your connection coming from?

Israel.

**Comment by davidfischer** [comment]
Thanks. The user reporting on Twitter appears to be from Germany. I don't know exactly what Microsoft's setup is but I would have expected Israel and Germany to not hit the same edge.

**Comment by heartsucker** [comment]
Seeing this too (TLS error):

```
$ uname -a
Linux pythagoras 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
$ firefox --version
Mozilla Firefox 62.0.2
```

**Comment by heartsucker** [comment]
Also:

```
$ curl -vvv https://assets.readthedocs.org/static/vendor/jquery-migrate.js
*   Trying 13.107.246.10...
* TCP_NODELAY set
* Connected to assets.readthedocs.org (13.107.246.10) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.azureedge.net
*  start date: Aug 16 04:29:12 2017 GMT
*  expire date: Aug 16 04:29:12 2019 GMT
*  subjectAltName does not match assets.readthedocs.org
* SSL: no alternative certificate subject name matches target host name 'assets.readthedocs.org'
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (51) SSL: no alternative certificate subject name matches target host name 'assets.readthedocs.org'
```

**Comment by davidfischer** [comment]
Thanks for the details @heartsucker.

**Comment by davidfischer** [comment]
Ok, I sshed into a bunch of different servers and found one (US East) that exhibits the issue. I don't think there's much I personally can do here so I'm going to try to escalate this to Microsoft.

**Comment by davidfischer** [comment]
In case anybody runs across this, we are still seeing this very intermittently. If you have any details on your setup (browser, country/region, OS) that would be helpful.

The command to test this in OpenSSL is:

    openssl s_client -connect assets.readthedocs.org:443 -showcerts -servername assets.readthedocs.org | grep CN=

If you see `CN=assets.readthedocs.org` in the response, it's good. If instead you see `*.azureedge.net` then it is not correct.

**Comment by heartsucker** [comment]
Still seeing this in Berlin.

```
$ openssl s_client -connect assets.readthedocs.org:443 -showcerts -servername assets.readthedocs.org
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT TLS CA 4
verify return:1
depth=0 CN = *.azureedge.net
verify return:1
---
Certificate chain
 0 s:/CN=*.azureedge.net
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 4
-----BEGIN CERTIFICATE-----
MIIHGTCCBQGgAwIBAgITFgAAJpSMKYT9Dku8agAAAAAmlDANBgkqhkiG9w0BAQsF
ADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UE
CxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgVExTIENBIDQw
HhcNMTcwODE2MDQyOTEyWhcNMTkwODE2MDQyOTEyWjAaMRgwFgYDVQQDDA8qLmF6
dXJlZWRnZS5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDedGNO
AOdLEOxyUAUDZ04qDc0R5J2I1tI8Fln5ULDEou2s8V99naDQfwaYxHMtdrGZSqLT
5W5L/cwfdhXs0AC/4SQQlu89OmvFt7LWEl8dOToZQrwMGtjLsoCJwZTwM0JRGZBr
wiydJUPBrRTXRLQMHklY4oh1mXWR9Pe2mszzU1RXD7Yt2KRD5luGVQjUunjhggY2
BfK7MapkoPjCVMJik94atdR3z4fh+tPO+CfhYKQSygVCVscOcuzBOr17xaaF2gme
iK/OelZX4RIkZBgXSH1x9H3kJZ9pCrA7KySR4yPyiHQ7rFyqPwhIci6uIAeW+q1T
+aP03ILagBkWfML9AgMBAAGjggLkMIIC4DAdBgNVHQ4EFgQU4N/UbSUydhbv1a0b
KeueB4wLPhEwCwYDVR0PBAQDAgSwMB8GA1UdIwQYMBaAFHp7jMHP56DKHNRr+vvh
M8MPGqKdMIGsBgNVHR8EgaQwgaEwgZ6ggZuggZiGS2h0dHA6Ly9tc2NybC5taWNy
b3NvZnQuY29tL3BraS9tc2NvcnAvY3JsL01pY3Jvc29mdCUyMElUJTIwVExTJTIw
Q0ElMjA0LmNybIZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9tc2NvcnAv
Y3JsL01pY3Jvc29mdCUyMElUJTIwVExTJTIwQ0ElMjA0LmNybDCBhQYIKwYBBQUH
AQEEeTB3MFEGCCsGAQUFBzAChkVodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
L21zY29ycC9NaWNyb3NvZnQlMjBJVCUyMFRMUyUyMENBJTIwNC5jcnQwIgYIKwYB
BQUHMAGGFmh0dHA6Ly9vY3NwLm1zb2NzcC5jb20wPgYJKwYBBAGCNxUHBDEwLwYn
KwYBBAGCNxUIh9qGdYPu2QGCyYUbgbWeYYX062CBXYTS30KC55N6AgFkAgEWMB0G
A1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATBNBgNVHSAERjBEMEIGCSsGAQQB
gjcqATA1MDMGCCsGAQUFBwIBFidodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
L21zY29ycC9jcHMwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEF
BQcDATCBggYDVR0RBHsweYIPKi5henVyZWVkZ2UubmV0ghsqLm1lZGlhLm1pY3Jv
c29mdHN0cmVhbS5jb22CIioub3JpZ2luLm1lZGlhc2VydmljZXMud2luZG93cy5u
ZXSCJSouc3RyZWFtaW5nLm1lZGlhc2VydmljZXMud2luZG93cy5uZXQwDQYJKoZI
hvcNAQELBQADggIBADeBv8a893gXj/6PM+fYCbQ9nlNdWSjBhjx8bW4qPjCNQKYr
Mpo4LRfsnHyekdjGRuSFQJZjzQ/a9evS7g0SA7tMwuZlZbnvomobstYxVgdvjI85
lsobfSTPVKrXlxv+78vhLmdptCxhaKeONHwXPaWDxrH4IYNpS+iQ4WXz3mH2QgHu
dvSWB8wYm0+za/68CiEuoMmTcBqa5F5lzoRZ9ClLlzXNaaq4shVccwOv8XuSMVZm
O6MdCMLIAXW4XTi3mRrFDvcrwQpF0vz7JxWefBd9iO9NR3LJv9JjqZWc7YWU3a62
/JisdyD1SXubNPxThTT4xz1tZFHWohaW/k8W0ydgp+sdrAuUwUbLF0m+4ZYsW/Id
dz11WsNkMliCP/zpNgktqEwgDBzSpTT95e/SEFsPBUxZFX0h+sG+ceMBxVIETOO/
i0qvZ93iRQSInP/fBiGVp1bDLrDom3zvmfCOFeYM4Rj/4PMATUp6K0Sweht43fcl
eoUxUUrMhqgeeg6BZuwV9Mr3w4hhGHe+wTVis+on2JWv5xn3JVl46oUSB0gfPz6g
Pu16Oj1AHWAcebgHfFU/CpjSilgAvNw+MnNQscYj/DvwE8D/OMOr4aqg9gcmQcRn
EN7spfIZ6pByK2pmAzN+qmWRA0fdlevu3xQX6kOz6Ggnph3TupMAhT1t9nxT
-----END CERTIFICATE-----
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 4
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
-----BEGIN CERTIFICATE-----
MIIFtDCCBJygAwIBAgIQC2qzsD6xqfbEYJJqqM3+szANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJJRTESMBAGA1UEChMJQmFsdGltb3JlMRMwEQYDVQQLEwpDeWJl
clRydXN0MSIwIAYDVQQDExlCYWx0aW1vcmUgQ3liZXJUcnVzdCBSb290MB4XDTE2
MDUyMDEyNTIzOFoXDTI0MDUyMDEyNTIzOFowgYsxCzAJBgNVBAYTAlVTMRMwEQYD
VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
b3NvZnQgQ29ycG9yYXRpb24xFTATBgNVBAsTDE1pY3Jvc29mdCBJVDEeMBwGA1UE
AxMVTWljcm9zb2Z0IElUIFRMUyBDQSA0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
MIICCgKCAgEAq+XrXaNrOZ71NIgSux1SJl19CQvGeY6rtw7fGbLd7g/27vRW5Ebi
kg/iZwvjHHGk1EFztMuZFo6/d32wrx5s7XEuwwh3Sl6Sruxa0EiB0MXpoPV6jx6N
XtOtksDaxpE1MSC5OQTNECo8lx0AnpkYGAnPS5fkyfwA8AxanTboskDBSqyEKKo9
Rhgrp4qs9K9LqH5JQsdiIMDmpztd65Afu4rYnJDjOrFswpTOPjJry3GzQS65xeFd
2FkngvvhSA1+6ATx+QEnQfqUWn3FMLu2utcRm4j6AcxuS5K5+Hg8y5xomhZmiNCT
sCqDLpcRHX6BIGHksLmbnG5TlZUixtm9dRC62XWMPD8d0Jb4M0V7ex9UM+VIl6cF
JKLb0dyVriAqfZaJSHuSetAksd5IEfdnPLTf+Fhg9U97NGjm/awmCLbzLEPbT8QW
0JsMcYexB2uG3Y+gsftm2tjL6fLwZeWO2BzqL7otZPFe0BtQsgyFSs87yC4qanWM
wK5c2enAfH182pzjvUqwYAeCK31dyBCvLmKM3Jr94dm5WUiXQhrDUIELH4Mia+Sb
vCkigv2AUVx1Xw41wt1/L3pnnz2OW4y7r530zAz7qB+dIcHz51IaXc4UV21QuEnu
sQsn0uJpJxJuxsAmPuekKxuLUzgG+hqHOuBLf5kWTlk9WWnxcadlZRsCAwEAAaOC
AUIwggE+MB0GA1UdDgQWBBR6e4zBz+egyhzUa/r74TPDDxqinTAfBgNVHSMEGDAW
gBTlnVkwgkdYzKz6CFQ2hns6tQRN8DASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1Ud
DwEB/wQEAwIBhjAnBgNVHSUEIDAeBggrBgEFBQcDAQYIKwYBBQUHAwIGCCsGAQUF
BwMJMDQGCCsGAQUFBwEBBCgwJjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGln
aWNlcnQuY29tMDoGA1UdHwQzMDEwL6AtoCuGKWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0
LmNvbS9PbW5pcm9vdDIwMjUuY3JsMD0GA1UdIAQ2MDQwMgYEVR0gADAqMCgGCCsG
AQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMA0GCSqGSIb3DQEB
CwUAA4IBAQAR/nIGOiEKN27I9SkiAmKeRQ7t+gaf77+eJDUX/jmIsrsB4Xjf0YuX
/bd38YpyT0k66LMp13SH5LnzF2CHiJJVgr3ZfRNIfwaQOolm552W95XNYA/X4cr2
du76mzVIoZh90pMqT4EWx6iWu9El86ZvUNoAmyqo9DUA4/0sO+3lFZt/Fg/Hjsk2
IJTwHQG5ElBQmYHgKEIsjnj/7cae1eTK6aCqs0hPpF/kixj/EwItkBE2GGYoOiKa
3pXxWe6fbSoXdZNQwwUS1d5ktLa829d2Wf6l1uVW4f5GXDuK+OwO++8SkJHOIBKB
ujxS43/jQPQMQSBmhxjaMmng9tyPKPK9
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=*.azureedge.net
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 4
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3743 bytes and written 300 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 4A07000094437BC02714FAB5AC8F268D3606FB58530F5B607228669B3CC8A79A
    Session-ID-ctx: 
    Master-Key: 400DC477230B8CC8AF96D19CC907C14505BD662B51370CF35C9C8F5DA9360165F6107848705EBC5B96A1DFF4982AABBF
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1537695384
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

**Comment by manikos** [comment]
Same here for FF 62.0, Linux Mint. The `openssl` response is: `0 s:/CN=*.azureedge.net`.

**Comment by romik-g** [comment]
Same problem, same CN, same IP `13.107.246.10` at the end of CNAME resolve like in [comment above](https://github.com/rtfd/readthedocs.org/issues/4660#issuecomment-423803780). Slovakia.

**Comment by int-ua** [comment]
Ukraine, `13.107.246.10`, `CN=*.azureedge.net`, Firefox 62.0 on Kubuntu.

**Comment by davidfischer** [comment]
I'm not able to reproduce this as of about an hour ago. I haven't gotten confirmation that it is resolved.

**Comment by agjohnson** [comment]
We got confirmation that the Azure team has repaired the CDN SSL termination. Can anyone still reproduce this issue or confirm the fix has worked? I wasn't able to reproduce this yesterday either, but that was locally here in the west US.

**Comment by int-ua** [comment]
Looks fixed here, thank you.

**Comment by agjohnson** [comment]
Going to close this then, but speak up if you're still hitting this issue still!
